#!/bin/bash

# Stop previous instance of the bot if it's running
pkill Yumiko;

# Build the bot
cd ~/Yumiko;
dotnet build -c Release --source=https://api.nuget.org/v3/index.json;

# Start the bot
cd ~/Yumiko/bin/Release/net7.0/;
./Yumiko;
