#!/bin/bash

# Stop previous instance of the bot if it's running
pkill Yumiko;

# Build the bot
cd ~/bots/Yumiko;
dotnet build -c Release --source=https://api.nuget.org/v3/index.json;

# Start the bot
cd ~/bots/Yumiko/bin/Release/net6.0/;
./Yumiko;
