//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YumikoBot.Data_Access_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CanalAnuncios
    {
        public long guild_id { get; set; }
        public long channel_id { get; set; }
    }
}
