//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YumikoBot.Data_Access_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioDiscord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UsuarioDiscord()
        {
            this.MostrarYear = true;
        }
    
        public long Id { get; set; }
        public long guild_id { get; set; }
        public System.DateTime Birthday { get; set; }
        public Nullable<bool> MostrarYear { get; set; }
    }
}
