//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yumiko {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yumiko.res.Translations.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s guilds.
        /// </summary>
        public static string bot_guilds {
            get {
                return ResourceManager.GetString("bot_guilds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have left the `{0}` guild ({1}).
        /// </summary>
        public static string bot_left_guild {
            get {
                return ResourceManager.GetString("bot_left_guild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error retrieving the guild with the Id: `{0}`.
        /// </summary>
        public static string error_retrieving_guild_with_id {
            get {
                return ResourceManager.GetString("error_retrieving_guild_with_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guild with id `{0}` not found.
        /// </summary>
        public static string guild_with_id_not_found {
            get {
                return ResourceManager.GetString("guild_with_id_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id `{0}` not valid.
        /// </summary>
        public static string id_not_valid {
            get {
                return ResourceManager.GetString("id_not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joined date.
        /// </summary>
        public static string joined_date {
            get {
                return ResourceManager.GetString("joined_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastest log file.
        /// </summary>
        public static string lastest_log_file {
            get {
                return ResourceManager.GetString("lastest_log_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member count.
        /// </summary>
        public static string member_count {
            get {
                return ResourceManager.GetString("member_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No logs found.
        /// </summary>
        public static string no_logs_found {
            get {
                return ResourceManager.GetString("no_logs_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutting down.
        /// </summary>
        public static string shutting_down {
            get {
                return ResourceManager.GetString("shutting_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total guilds.
        /// </summary>
        public static string total_guilds {
            get {
                return ResourceManager.GetString("total_guilds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total users.
        /// </summary>
        public static string total_users {
            get {
                return ResourceManager.GetString("total_users", resourceCulture);
            }
        }
    }
}
