//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yumiko {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yumiko.res.Translations.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action cancelled.
        /// </summary>
        public static string action_cancelled {
            get {
                return ResourceManager.GetString("action_cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action cannot be undone.
        /// </summary>
        public static string action_cannont_be_undone {
            get {
                return ResourceManager.GetString("action_cannont_be_undone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anilist profile deleted successfully.
        /// </summary>
        public static string anilist_profile_deleted_successfully {
            get {
                return ResourceManager.GetString("anilist_profile_deleted_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anilist profile not found.
        /// </summary>
        public static string anilist_profile_not_found {
            get {
                return ResourceManager.GetString("anilist_profile_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animated.
        /// </summary>
        public static string animated {
            get {
                return ResourceManager.GetString("animated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anime list.
        /// </summary>
        public static string anime_list {
            get {
                return ResourceManager.GetString("anime_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anime stats.
        /// </summary>
        public static string anime_stats {
            get {
                return ResourceManager.GetString("anime_stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string answer {
            get {
                return ResourceManager.GetString("answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badges.
        /// </summary>
        public static string badges {
            get {
                return ResourceManager.GetString("badges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is an anime trivia bot, with other games and funcionalities.
        /// </summary>
        public static string bot_about {
            get {
                return ResourceManager.GetString("bot_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s guilds.
        /// </summary>
        public static string bot_guilds {
            get {
                return ResourceManager.GetString("bot_guilds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have left the `{0}` guild ({1}).
        /// </summary>
        public static string bot_left_guild {
            get {
                return ResourceManager.GetString("bot_left_guild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapters.
        /// </summary>
        public static string chapters {
            get {
                return ResourceManager.GetString("chapters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character not found.
        /// </summary>
        public static string character_not_found {
            get {
                return ResourceManager.GetString("character_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string color {
            get {
                return ResourceManager.GetString("color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm that you want to delete your profile.
        /// </summary>
        public static string confirm_delete_profile {
            get {
                return ResourceManager.GetString("confirm_delete_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm that you want to save this profile.
        /// </summary>
        public static string confirm_save_profile {
            get {
                return ResourceManager.GetString("confirm_save_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation date.
        /// </summary>
        public static string creation_date {
            get {
                return ResourceManager.GetString("creation_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emote `{0}` not found.
        /// </summary>
        public static string emote_not_found {
            get {
                return ResourceManager.GetString("emote_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Episode.
        /// </summary>
        public static string episode {
            get {
                return ResourceManager.GetString("episode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Episodes.
        /// </summary>
        public static string episodes {
            get {
                return ResourceManager.GetString("episodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error retrieving the guild with the Id: `{0}`.
        /// </summary>
        public static string error_retrieving_guild_with_id {
            get {
                return ResourceManager.GetString("error_retrieving_guild_with_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example.
        /// </summary>
        public static string example {
            get {
                return ResourceManager.GetString("example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External &amp; Streaming links.
        /// </summary>
        public static string external_links {
            get {
                return ResourceManager.GetString("external_links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite animes.
        /// </summary>
        public static string favorite_animes {
            get {
                return ResourceManager.GetString("favorite_animes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite characters.
        /// </summary>
        public static string favorite_characters {
            get {
                return ResourceManager.GetString("favorite_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite mangas.
        /// </summary>
        public static string favorite_mangas {
            get {
                return ResourceManager.GetString("favorite_mangas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite staff.
        /// </summary>
        public static string favorite_staff {
            get {
                return ResourceManager.GetString("favorite_staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite studios.
        /// </summary>
        public static string favorite_studios {
            get {
                return ResourceManager.GetString("favorite_studios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feels like.
        /// </summary>
        public static string feels_like {
            get {
                return ResourceManager.GetString("feels_like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string format {
            get {
                return ResourceManager.GetString("format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genres.
        /// </summary>
        public static string genres {
            get {
                return ResourceManager.GetString("genres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guild with id `{0}` not found.
        /// </summary>
        public static string guild_with_id_not_found {
            get {
                return ResourceManager.GetString("guild_with_id_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity.
        /// </summary>
        public static string humidity {
            get {
                return ResourceManager.GetString("humidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id `{0}` not valid.
        /// </summary>
        public static string id_not_valid {
            get {
                return ResourceManager.GetString("id_not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image extension must be JPG, PNG or JPEG.
        /// </summary>
        public static string image_format_error {
            get {
                return ResourceManager.GetString("image_format_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This image is from an adult anime.
        /// </summary>
        public static string image_from_nsfw_anime {
            get {
                return ResourceManager.GetString("image_from_nsfw_anime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter the link of an image.
        /// </summary>
        public static string image_must_enter_link {
            get {
                return ResourceManager.GetString("image_must_enter_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in popularity rank.
        /// </summary>
        public static string in_popularity_rank {
            get {
                return ResourceManager.GetString("in_popularity_rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite.
        /// </summary>
        public static string invite {
            get {
                return ResourceManager.GetString("invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join date.
        /// </summary>
        public static string join_date {
            get {
                return ResourceManager.GetString("join_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joined date.
        /// </summary>
        public static string joined_date {
            get {
                return ResourceManager.GetString("joined_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastest log file.
        /// </summary>
        public static string lastest_log_file {
            get {
                return ResourceManager.GetString("lastest_log_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string link {
            get {
                return ResourceManager.GetString("link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location `{0}, {1}` not found.
        /// </summary>
        public static string location_not_found {
            get {
                return ResourceManager.GetString("location_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get away! You two are going to kill each other.
        /// </summary>
        public static string love_0 {
            get {
                return ResourceManager.GetString("love_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to They will hate each other, they are not compatible at all.
        /// </summary>
        public static string love_10 {
            get {
                return ResourceManager.GetString("love_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfect relationship! They will marry and have many children.
        /// </summary>
        public static string love_100 {
            get {
                return ResourceManager.GetString("love_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is best that they move away from each other, they do not fit.
        /// </summary>
        public static string love_25 {
            get {
                return ResourceManager.GetString("love_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to They will be good friends, but I find love difficult.
        /// </summary>
        public static string love_50 {
            get {
                return ResourceManager.GetString("love_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most likely they are best friends and hopefully something more.
        /// </summary>
        public static string love_75 {
            get {
                return ResourceManager.GetString("love_75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to They have to give themselves a chance.
        /// </summary>
        public static string love_90 {
            get {
                return ResourceManager.GetString("love_90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You two are meant to be together.
        /// </summary>
        public static string love_99 {
            get {
                return ResourceManager.GetString("love_99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Love between **{0}** and **{1}**.
        /// </summary>
        public static string love_between {
            get {
                return ResourceManager.GetString("love_between", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manga list.
        /// </summary>
        public static string manga_list {
            get {
                return ResourceManager.GetString("manga_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manga stats.
        /// </summary>
        public static string manga_stats {
            get {
                return ResourceManager.GetString("manga_stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean score.
        /// </summary>
        public static string mean_score {
            get {
                return ResourceManager.GetString("mean_score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s avatar.
        /// </summary>
        public static string member_avatar {
            get {
                return ResourceManager.GetString("member_avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member count.
        /// </summary>
        public static string member_count {
            get {
                return ResourceManager.GetString("member_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message.
        /// </summary>
        public static string message {
            get {
                return ResourceManager.GetString("message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min/Max.
        /// </summary>
        public static string min_max {
            get {
                return ResourceManager.GetString("min_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        public static string minute {
            get {
                return ResourceManager.GetString("minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, you must enter the URL of your Anilist profile.
        /// </summary>
        public static string must_enter_anilist_profile_url {
            get {
                return ResourceManager.GetString("must_enter_anilist_profile_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My love to **{0}** is **{1}%**.
        /// </summary>
        public static string my_love_to_user_is {
            get {
                return ResourceManager.GetString("my_love_to_user_is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, you decided to not save your Anilist profile.
        /// </summary>
        public static string new_profile_cancelled_mention {
            get {
                return ResourceManager.GetString("new_profile_cancelled_mention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New profile saved successfully.
        /// </summary>
        public static string new_profile_saved {
            get {
                return ResourceManager.GetString("new_profile_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, you have successfully saved your Anilist profile.
        /// </summary>
        public static string new_profile_saved_mention {
            get {
                return ResourceManager.GetString("new_profile_saved_mention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, you don&apos;t have any Anilist profile vinculated .
        /// </summary>
        public static string no_anilist_profile_vinculated {
            get {
                return ResourceManager.GetString("no_anilist_profile_vinculated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No logs found.
        /// </summary>
        public static string no_logs_found {
            get {
                return ResourceManager.GetString("no_logs_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found for this image.
        /// </summary>
        public static string no_results_found_image {
            get {
                return ResourceManager.GetString("no_results_found_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string options {
            get {
                return ResourceManager.GetString("options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure.
        /// </summary>
        public static string pressure {
            get {
                return ResourceManager.GetString("pressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string privacy_policy {
            get {
                return ResourceManager.GetString("privacy_policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string processing {
            get {
                return ResourceManager.GetString("processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait while the command is processed.
        /// </summary>
        public static string processing_desc {
            get {
                return ResourceManager.GetString("processing_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing image.
        /// </summary>
        public static string processing_image {
            get {
                return ResourceManager.GetString("processing_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string profile {
            get {
                return ResourceManager.GetString("profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publication date.
        /// </summary>
        public static string publication_date {
            get {
                return ResourceManager.GetString("publication_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string question {
            get {
                return ResourceManager.GetString("question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random kitten.
        /// </summary>
        public static string random_cat {
            get {
                return ResourceManager.GetString("random_cat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error trying to retrieve the kitten.
        /// </summary>
        public static string random_cat_error {
            get {
                return ResourceManager.GetString("random_cat_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random dog.
        /// </summary>
        public static string random_dog {
            get {
                return ResourceManager.GetString("random_dog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error trying to retrieve the dog.
        /// </summary>
        public static string random_dog_error {
            get {
                return ResourceManager.GetString("random_dog_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered.
        /// </summary>
        public static string registered {
            get {
                return ResourceManager.GetString("registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieved from.
        /// </summary>
        public static string retrieved_from {
            get {
                return ResourceManager.GetString("retrieved_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string roles {
            get {
                return ResourceManager.GetString("roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember that it only works with images that are part of an anime episode.
        /// </summary>
        public static string sauce_remember {
            get {
                return ResourceManager.GetString("sauce_remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string score {
            get {
                return ResourceManager.GetString("score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutting down.
        /// </summary>
        public static string shutting_down {
            get {
                return ResourceManager.GetString("shutting_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similarity.
        /// </summary>
        public static string similarity {
            get {
                return ResourceManager.GetString("similarity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string start_date {
            get {
                return ResourceManager.GetString("start_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studios.
        /// </summary>
        public static string studios {
            get {
                return ResourceManager.GetString("studios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunrise.
        /// </summary>
        public static string sunrise {
            get {
                return ResourceManager.GetString("sunrise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunset.
        /// </summary>
        public static string sunset {
            get {
                return ResourceManager.GetString("sunset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synonyms.
        /// </summary>
        public static string synonyms {
            get {
                return ResourceManager.GetString("synonyms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string tags {
            get {
                return ResourceManager.GetString("tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string temperature {
            get {
                return ResourceManager.GetString("temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The possible anime of the image is.
        /// </summary>
        public static string the_possible_anime_is {
            get {
                return ResourceManager.GetString("the_possible_anime_is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titles language.
        /// </summary>
        public static string titles_language {
            get {
                return ResourceManager.GetString("titles_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To vinculate your profile, you must use the following command.
        /// </summary>
        public static string to_vinculate_anilist_profile {
            get {
                return ResourceManager.GetString("to_vinculate_anilist_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total guilds.
        /// </summary>
        public static string total_guilds {
            get {
                return ResourceManager.GetString("total_guilds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total users.
        /// </summary>
        public static string total_users {
            get {
                return ResourceManager.GetString("total_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        public static string unknown_error {
            get {
                return ResourceManager.GetString("unknown_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error retrieving image from trace.moe.
        /// </summary>
        public static string unknown_error_tracemoe {
            get {
                return ResourceManager.GetString("unknown_error_tracemoe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please use this command in a age-restricted channel.
        /// </summary>
        public static string use_command_in_nsfw_channel {
            get {
                return ResourceManager.GetString("use_command_in_nsfw_channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string video {
            get {
                return ResourceManager.GetString("video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote.
        /// </summary>
        public static string vote {
            get {
                return ResourceManager.GetString("vote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am completely in love with you, when do we get married?.
        /// </summary>
        public static string waifu_level_100 {
            get {
                return ResourceManager.GetString("waifu_level_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I will shot myself before touch you.
        /// </summary>
        public static string waifu_level_25 {
            get {
                return ResourceManager.GetString("waifu_level_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You make me sick, I better get away from you.
        /// </summary>
        public static string waifu_level_50 {
            get {
                return ResourceManager.GetString("waifu_level_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not bad, maybe you have a chance with me.
        /// </summary>
        public static string waifu_level_75 {
            get {
                return ResourceManager.GetString("waifu_level_75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am your waifu, you can do what you want with me.
        /// </summary>
        public static string waifu_level_99 {
            get {
                return ResourceManager.GetString("waifu_level_99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather.
        /// </summary>
        public static string weather {
            get {
                return ResourceManager.GetString("weather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather in.
        /// </summary>
        public static string weather_in {
            get {
                return ResourceManager.GetString("weather_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string website {
            get {
                return ResourceManager.GetString("website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind speed.
        /// </summary>
        public static string wind_speed {
            get {
                return ResourceManager.GetString("wind_speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Without animes or mangas).
        /// </summary>
        public static string without_animes_or_mangas {
            get {
                return ResourceManager.GetString("without_animes_or_mangas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Without description).
        /// </summary>
        public static string without_description {
            get {
                return ResourceManager.GetString("without_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without titles.
        /// </summary>
        public static string without_titles {
            get {
                return ResourceManager.GetString("without_titles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YES OR NO?.
        /// </summary>
        public static string yes_or_no {
            get {
                return ResourceManager.GetString("yes_or_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Anilist profile is.
        /// </summary>
        public static string your_anilist_profile_is {
            get {
                return ResourceManager.GetString("your_anilist_profile_is", resourceCulture);
            }
        }
    }
}
