//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yumiko {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal translations() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yumiko.res.Translations.translations", typeof(translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Access denied.
        /// </summary>
        public static string access_denied {
            get {
                return ResourceManager.GetString("access_denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This action cannot be undone.
        /// </summary>
        public static string action_cannont_be_undone {
            get {
                return ResourceManager.GetString("action_cannont_be_undone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adult content.
        /// </summary>
        public static string adult_content {
            get {
                return ResourceManager.GetString("adult_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Age.
        /// </summary>
        public static string age {
            get {
                return ResourceManager.GetString("age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anilist profile deleted successfully.
        /// </summary>
        public static string anilist_profile_deleted_successfully {
            get {
                return ResourceManager.GetString("anilist_profile_deleted_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anilist profile not found.
        /// </summary>
        public static string anilist_profile_not_found {
            get {
                return ResourceManager.GetString("anilist_profile_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a **Instructions**.
        /// </summary>
        public static string anilist_setprofile_instructions {
            get {
                return ResourceManager.GetString("anilist_setprofile_instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1- Click on the **Authorize** button.
        /// </summary>
        public static string anilist_setprofile_instructions_1 {
            get {
                return ResourceManager.GetString("anilist_setprofile_instructions_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2- Once the web page opens, click on the **Authorize** green button and then copy the text that will appear to copy.
        /// </summary>
        public static string anilist_setprofile_instructions_2 {
            get {
                return ResourceManager.GetString("anilist_setprofile_instructions_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 3- Close the web page and click on the **Paste code here** button.
        /// </summary>
        public static string anilist_setprofile_instructions_3 {
            get {
                return ResourceManager.GetString("anilist_setprofile_instructions_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 4- Paste the code in the modal and submit it.
        /// </summary>
        public static string anilist_setprofile_instructions_4 {
            get {
                return ResourceManager.GetString("anilist_setprofile_instructions_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Animated.
        /// </summary>
        public static string animated {
            get {
                return ResourceManager.GetString("animated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anime.
        /// </summary>
        public static string anime {
            get {
                return ResourceManager.GetString("anime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anime list.
        /// </summary>
        public static string anime_list {
            get {
                return ResourceManager.GetString("anime_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anime stats.
        /// </summary>
        public static string anime_stats {
            get {
                return ResourceManager.GetString("anime_stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anonymous vote.
        /// </summary>
        public static string anonymous_poll {
            get {
                return ResourceManager.GetString("anonymous_poll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Another trivia is already running in this channel.
        /// </summary>
        public static string another_trivia_playing {
            get {
                return ResourceManager.GetString("another_trivia_playing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a If you want to play a new trivia game, cancel de actual one or run this command on another channel.
        /// </summary>
        public static string another_trivia_playing_desc {
            get {
                return ResourceManager.GetString("another_trivia_playing_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Answer.
        /// </summary>
        public static string answer {
            get {
                return ResourceManager.GetString("answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Authorize.
        /// </summary>
        public static string authorize {
            get {
                return ResourceManager.GetString("authorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Badges.
        /// </summary>
        public static string badges {
            get {
                return ResourceManager.GetString("badges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} is an anime trivia bot, with other games and funcionalities.
        /// </summary>
        public static string bot_about {
            get {
                return ResourceManager.GetString("bot_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0}&apos;s servers.
        /// </summary>
        public static string bot_guilds {
            get {
                return ResourceManager.GetString("bot_guilds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I have left the `{0}` server ({1}).
        /// </summary>
        public static string bot_left_guild {
            get {
                return ResourceManager.GetString("bot_left_guild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bot permission required.
        /// </summary>
        public static string bot_permission_required {
            get {
                return ResourceManager.GetString("bot_permission_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} need the `{1}` permission to execute this command.
        /// </summary>
        public static string bot_permission_required_desc {
            get {
                return ResourceManager.GetString("bot_permission_required_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0}&apos;s statistics.
        /// </summary>
        public static string bot_stats {
            get {
                return ResourceManager.GetString("bot_stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You cant play versus a bot.
        /// </summary>
        public static string cant_play_vs_bot {
            get {
                return ResourceManager.GetString("cant_play_vs_bot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chapters.
        /// </summary>
        public static string chapters {
            get {
                return ResourceManager.GetString("chapters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Character.
        /// </summary>
        public static string character {
            get {
                return ResourceManager.GetString("character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a characters.
        /// </summary>
        public static string characters {
            get {
                return ResourceManager.GetString("characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Choose an option.
        /// </summary>
        public static string choose_an_option {
            get {
                return ResourceManager.GetString("choose_an_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code.
        /// </summary>
        public static string code {
            get {
                return ResourceManager.GetString("code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color.
        /// </summary>
        public static string color {
            get {
                return ResourceManager.GetString("color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No command were used.
        /// </summary>
        public static string commands_not_used {
            get {
                return ResourceManager.GetString("commands_not_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Commands used.
        /// </summary>
        public static string commands_used {
            get {
                return ResourceManager.GetString("commands_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm that you want to delete your profile.
        /// </summary>
        public static string confirm_delete_profile {
            get {
                return ResourceManager.GetString("confirm_delete_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm if you really want to delete your stats.
        /// </summary>
        public static string confirm_delete_stats {
            get {
                return ResourceManager.GetString("confirm_delete_stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creating poll.
        /// </summary>
        public static string creating_poll {
            get {
                return ResourceManager.GetString("creating_poll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creation date.
        /// </summary>
        public static string creation_date {
            get {
                return ResourceManager.GetString("creation_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date of birth.
        /// </summary>
        public static string date_of_birth {
            get {
                return ResourceManager.GetString("date_of_birth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date of death.
        /// </summary>
        public static string date_of_death {
            get {
                return ResourceManager.GetString("date_of_death", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Defeat!.
        /// </summary>
        public static string defeat {
            get {
                return ResourceManager.GetString("defeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have chosen not to delete their statistics.
        /// </summary>
        public static string delete_stats_cancelled {
            get {
                return ResourceManager.GetString("delete_stats_cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have deleted all your statistics on this server.
        /// </summary>
        public static string delete_stats_done {
            get {
                return ResourceManager.GetString("delete_stats_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You did not press the button to write!.
        /// </summary>
        public static string did_not_press_button_to_write {
            get {
                return ResourceManager.GetString("did_not_press_button_to_write", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You did not write on time!.
        /// </summary>
        public static string did_not_write_on_time {
            get {
                return ResourceManager.GetString("did_not_write_on_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Difficulty.
        /// </summary>
        public static string difficulty {
            get {
                return ResourceManager.GetString("difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Direct message required.
        /// </summary>
        public static string dm_required {
            get {
                return ResourceManager.GetString("dm_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can only execute this command in direct messages.
        /// </summary>
        public static string dm_required_desc {
            get {
                return ResourceManager.GetString("dm_required_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Emote `{0}` not found.
        /// </summary>
        public static string emote_not_found {
            get {
                return ResourceManager.GetString("emote_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a End date.
        /// </summary>
        public static string end_date {
            get {
                return ResourceManager.GetString("end_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Episode.
        /// </summary>
        public static string episode {
            get {
                return ResourceManager.GetString("episode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Episodes.
        /// </summary>
        public static string episodes {
            get {
                return ResourceManager.GetString("episodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can only make up to 25 options.
        /// </summary>
        public static string error_max_options_limit {
            get {
                return ResourceManager.GetString("error_max_options_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have to make more than 1 option. Example: option 1, option 2, option 3.
        /// </summary>
        public static string error_more_than_one_option {
            get {
                return ResourceManager.GetString("error_more_than_one_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There was an error retrieving the server with the Id: `{0}`.
        /// </summary>
        public static string error_retrieving_guild_with_id {
            get {
                return ResourceManager.GetString("error_retrieving_guild_with_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a External &amp; Streaming links.
        /// </summary>
        public static string external_links {
            get {
                return ResourceManager.GetString("external_links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Favorite animes.
        /// </summary>
        public static string favorite_animes {
            get {
                return ResourceManager.GetString("favorite_animes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Favorite characters.
        /// </summary>
        public static string favorite_characters {
            get {
                return ResourceManager.GetString("favorite_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Favorite mangas.
        /// </summary>
        public static string favorite_mangas {
            get {
                return ResourceManager.GetString("favorite_mangas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Favorite staff.
        /// </summary>
        public static string favorite_staff {
            get {
                return ResourceManager.GetString("favorite_staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Favorite studios.
        /// </summary>
        public static string favorite_studios {
            get {
                return ResourceManager.GetString("favorite_studios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Feels like.
        /// </summary>
        public static string feels_like {
            get {
                return ResourceManager.GetString("feels_like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finish game.
        /// </summary>
        public static string finish_game {
            get {
                return ResourceManager.GetString("finish_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Format.
        /// </summary>
        public static string format {
            get {
                return ResourceManager.GetString("format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a From.
        /// </summary>
        public static string from {
            get {
                return ResourceManager.GetString("from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a from the anime.
        /// </summary>
        public static string from_the_anime {
            get {
                return ResourceManager.GetString("from_the_anime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Game cancelled.
        /// </summary>
        public static string game_cancelled {
            get {
                return ResourceManager.GetString("game_cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Games.
        /// </summary>
        public static string games {
            get {
                return ResourceManager.GetString("games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gender.
        /// </summary>
        public static string gender {
            get {
                return ResourceManager.GetString("gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Genre.
        /// </summary>
        public static string genre {
            get {
                return ResourceManager.GetString("genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Genres.
        /// </summary>
        public static string genres {
            get {
                return ResourceManager.GetString("genres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guess.
        /// </summary>
        public static string guess {
            get {
                return ResourceManager.GetString("guess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guess the.
        /// </summary>
        public static string guess_the {
            get {
                return ResourceManager.GetString("guess_the", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guess the anime.
        /// </summary>
        public static string guess_the_anime {
            get {
                return ResourceManager.GetString("guess_the_anime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guess the character.
        /// </summary>
        public static string guess_the_character {
            get {
                return ResourceManager.GetString("guess_the_character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guess the genre.
        /// </summary>
        public static string guess_the_genre {
            get {
                return ResourceManager.GetString("guess_the_genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guess the manga.
        /// </summary>
        public static string guess_the_manga {
            get {
                return ResourceManager.GetString("guess_the_manga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guess the protagonist.
        /// </summary>
        public static string guess_the_protagonist {
            get {
                return ResourceManager.GetString("guess_the_protagonist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guess the anime studio.
        /// </summary>
        public static string guess_the_studio {
            get {
                return ResourceManager.GetString("guess_the_studio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} has guessed it!.
        /// </summary>
        public static string guess_user {
            get {
                return ResourceManager.GetString("guess_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guesses.
        /// </summary>
        public static string guesses {
            get {
                return ResourceManager.GetString("guesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Server required.
        /// </summary>
        public static string guild_required {
            get {
                return ResourceManager.GetString("guild_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can only execute this command in a server.
        /// </summary>
        public static string guild_required_desc {
            get {
                return ResourceManager.GetString("guild_required_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Server with id `{0}` was not found.
        /// </summary>
        public static string guild_with_id_not_found {
            get {
                return ResourceManager.GetString("guild_with_id_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hangman.
        /// </summary>
        public static string hangman {
            get {
                return ResourceManager.GetString("hangman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Choose the anime with the best score to win!.
        /// </summary>
        public static string higher_or_lower_desc {
            get {
                return ResourceManager.GetString("higher_or_lower_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Choose the more popular anime to win!.
        /// </summary>
        public static string higher_or_lower_desc_popularity {
            get {
                return ResourceManager.GetString("higher_or_lower_desc_popularity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a **{0}** has lower avarage score **({1}/10)** than **{2} ({3}/10)**.
        /// </summary>
        public static string higher_or_lower_round_defeat {
            get {
                return ResourceManager.GetString("higher_or_lower_round_defeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string higher_or_lower_round_defeat_popularity {
            get {
                return ResourceManager.GetString("higher_or_lower_round_defeat_popularity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a **{0}** has **{1}/10** avarage score while **{2}** has **{3}/10**.
        /// </summary>
        public static string higher_or_lower_round_win {
            get {
                return ResourceManager.GetString("higher_or_lower_round_win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string higher_or_lower_round_win_popularity {
            get {
                return ResourceManager.GetString("higher_or_lower_round_win_popularity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hint!.
        /// </summary>
        public static string hint {
            get {
                return ResourceManager.GetString("hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Humidity.
        /// </summary>
        public static string humidity {
            get {
                return ResourceManager.GetString("humidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id `{0}` not valid.
        /// </summary>
        public static string id_not_valid {
            get {
                return ResourceManager.GetString("id_not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The image extension must be JPG, PNG or JPEG.
        /// </summary>
        public static string image_format_error {
            get {
                return ResourceManager.GetString("image_format_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This image is from an adult anime.
        /// </summary>
        public static string image_from_nsfw_anime {
            get {
                return ResourceManager.GetString("image_from_nsfw_anime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must enter the link of an image.
        /// </summary>
        public static string image_must_enter_link {
            get {
                return ResourceManager.GetString("image_must_enter_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a In english.
        /// </summary>
        public static string in_english {
            get {
                return ResourceManager.GetString("in_english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a in popularity rank.
        /// </summary>
        public static string in_popularity_rank {
            get {
                return ResourceManager.GetString("in_popularity_rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invite.
        /// </summary>
        public static string invite {
            get {
                return ResourceManager.GetString("invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Joined date.
        /// </summary>
        public static string joined_date {
            get {
                return ResourceManager.GetString("joined_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lastest log file.
        /// </summary>
        public static string lastest_log_file {
            get {
                return ResourceManager.GetString("lastest_log_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Latency.
        /// </summary>
        public static string latency {
            get {
                return ResourceManager.GetString("latency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Letters used.
        /// </summary>
        public static string letters_used {
            get {
                return ResourceManager.GetString("letters_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Library.
        /// </summary>
        public static string library {
            get {
                return ResourceManager.GetString("library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Link.
        /// </summary>
        public static string link {
            get {
                return ResourceManager.GetString("link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Link for.
        /// </summary>
        public static string link_for {
            get {
                return ResourceManager.GetString("link_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Location `{0}, {1}` not found.
        /// </summary>
        public static string location_not_found {
            get {
                return ResourceManager.GetString("location_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Get away! You two are going to kill each other.
        /// </summary>
        public static string love_0 {
            get {
                return ResourceManager.GetString("love_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a They will hate each other, they are not compatible at all.
        /// </summary>
        public static string love_10 {
            get {
                return ResourceManager.GetString("love_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfect relationship! They will marry and have many children.
        /// </summary>
        public static string love_100 {
            get {
                return ResourceManager.GetString("love_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a It is best that they move away from each other, they do not fit.
        /// </summary>
        public static string love_25 {
            get {
                return ResourceManager.GetString("love_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a They will be good friends, but I find love difficult.
        /// </summary>
        public static string love_50 {
            get {
                return ResourceManager.GetString("love_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Most likely they are best friends and hopefully something more.
        /// </summary>
        public static string love_75 {
            get {
                return ResourceManager.GetString("love_75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a They have to give themselves a chance.
        /// </summary>
        public static string love_90 {
            get {
                return ResourceManager.GetString("love_90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You two are meant to be together.
        /// </summary>
        public static string love_99 {
            get {
                return ResourceManager.GetString("love_99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Love between **{0}** and **{1}**.
        /// </summary>
        public static string love_between {
            get {
                return ResourceManager.GetString("love_between", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manga.
        /// </summary>
        public static string manga {
            get {
                return ResourceManager.GetString("manga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manga list.
        /// </summary>
        public static string manga_list {
            get {
                return ResourceManager.GetString("manga_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manga stats.
        /// </summary>
        public static string manga_stats {
            get {
                return ResourceManager.GetString("manga_stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mean score.
        /// </summary>
        public static string mean_score {
            get {
                return ResourceManager.GetString("mean_score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} recommendations.
        /// </summary>
        public static string media_recommendations {
            get {
                return ResourceManager.GetString("media_recommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Explanation: The higher the number, the more likely you are to like it. Recommendations are calculated based on your watched {0}s and the scores you have assigned to them..
        /// </summary>
        public static string media_recommendations_explanation {
            get {
                return ResourceManager.GetString("media_recommendations_explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0}&apos;s avatar.
        /// </summary>
        public static string member_avatar {
            get {
                return ResourceManager.GetString("member_avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Member count.
        /// </summary>
        public static string member_count {
            get {
                return ResourceManager.GetString("member_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Memory usage.
        /// </summary>
        public static string memory_usage {
            get {
                return ResourceManager.GetString("memory_usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This message will not be triggered if the user has voted in the past 12 hours.
        /// </summary>
        public static string message_will_not_be_triggered {
            get {
                return ResourceManager.GetString("message_will_not_be_triggered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minute.
        /// </summary>
        public static string minute {
            get {
                return ResourceManager.GetString("minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0}, wrong choice!.
        /// </summary>
        public static string miss_user_games {
            get {
                return ResourceManager.GetString("miss_user_games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a My love to **{0}** is **{1}%**.
        /// </summary>
        public static string my_love_to_user_is {
            get {
                return ResourceManager.GetString("my_love_to_user_is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New profile saved successfully.
        /// </summary>
        public static string new_profile_saved {
            get {
                return ResourceManager.GetString("new_profile_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0}, you have successfully saved your Anilist profile.
        /// </summary>
        public static string new_profile_saved_mention {
            get {
                return ResourceManager.GetString("new_profile_saved_mention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New record.
        /// </summary>
        public static string new_record {
            get {
                return ResourceManager.GetString("new_record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Congratulations {0}! You have beaten your best score.\n\nYour new record is: **{1}**.
        /// </summary>
        public static string new_record_desc {
            get {
                return ResourceManager.GetString("new_record_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is no active game in this channel.
        /// </summary>
        public static string no_active_game {
            get {
                return ResourceManager.GetString("no_active_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0}, you don&apos;t have any Anilist profile vinculated .
        /// </summary>
        public static string no_anilist_profile_vinculated {
            get {
                return ResourceManager.GetString("no_anilist_profile_vinculated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} seconds have passed and no answer has been given in time.
        /// </summary>
        public static string no_answser_in_time {
            get {
                return ResourceManager.GetString("no_answser_in_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nobody has clicked any button.
        /// </summary>
        public static string no_click_button {
            get {
                return ResourceManager.GetString("no_click_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There is no trivia in this channel.
        /// </summary>
        public static string no_current_trivia {
            get {
                return ResourceManager.GetString("no_current_trivia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No genre has been selected.
        /// </summary>
        public static string no_genre_selected {
            get {
                return ResourceManager.GetString("no_genre_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No logs found.
        /// </summary>
        public static string no_logs_found {
            get {
                return ResourceManager.GetString("no_logs_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No one has voted.
        /// </summary>
        public static string no_one_has_voted {
            get {
                return ResourceManager.GetString("no_one_has_voted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No recommendations were found. This is probably because you have few entries in your list or do not have a score assigned to them..
        /// </summary>
        public static string no_recommendations_found {
            get {
                return ResourceManager.GetString("no_recommendations_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No results found for this image.
        /// </summary>
        public static string no_results_found_image {
            get {
                return ResourceManager.GetString("no_results_found_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have not played any game yet.
        /// </summary>
        public static string no_stats_available {
            get {
                return ResourceManager.GetString("no_stats_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nobody has guessed.
        /// </summary>
        public static string nobody_has_guessed {
            get {
                return ResourceManager.GetString("nobody_has_guessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Not assigned.
        /// </summary>
        public static string not_assigned {
            get {
                return ResourceManager.GetString("not_assigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} not found.
        /// </summary>
        public static string not_found {
            get {
                return ResourceManager.GetString("not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No yet released.
        /// </summary>
        public static string not_yet_released {
            get {
                return ResourceManager.GetString("not_yet_released", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notes.
        /// </summary>
        public static string notes {
            get {
                return ResourceManager.GetString("notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NSFW Required.
        /// </summary>
        public static string nsfw_required {
            get {
                return ResourceManager.GetString("nsfw_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a of.
        /// </summary>
        public static string of {
            get {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Only the bot owner can execute this command.
        /// </summary>
        public static string only_bot_owner {
            get {
                return ResourceManager.GetString("only_bot_owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Options.
        /// </summary>
        public static string options {
            get {
                return ResourceManager.GetString("options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paste code here.
        /// </summary>
        public static string paste_code_here {
            get {
                return ResourceManager.GetString("paste_code_here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permission required.
        /// </summary>
        public static string permission_required {
            get {
                return ResourceManager.GetString("permission_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You and {0} needs the `{1}` permission to execute this command.
        /// </summary>
        public static string permission_required_desc {
            get {
                return ResourceManager.GetString("permission_required_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0}&apos;s turn.
        /// </summary>
        public static string player_turn {
            get {
                return ResourceManager.GetString("player_turn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please wait while everything is prepared.
        /// </summary>
        public static string please_wait {
            get {
                return ResourceManager.GetString("please_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Poll.
        /// </summary>
        public static string poll {
            get {
                return ResourceManager.GetString("poll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select an option to vote.
        /// </summary>
        public static string poll_description {
            get {
                return ResourceManager.GetString("poll_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Poll finished.
        /// </summary>
        public static string poll_finished {
            get {
                return ResourceManager.GetString("poll_finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Options separated by commas. Example: option 1, option 2, option 3.
        /// </summary>
        public static string poll_options_placeholder {
            get {
                return ResourceManager.GetString("poll_options_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Title of the poll.
        /// </summary>
        public static string poll_title_placeholder {
            get {
                return ResourceManager.GetString("poll_title_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pressure.
        /// </summary>
        public static string pressure {
            get {
                return ResourceManager.GetString("pressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Privacy Policy.
        /// </summary>
        public static string privacy_policy {
            get {
                return ResourceManager.GetString("privacy_policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Processing.
        /// </summary>
        public static string processing {
            get {
                return ResourceManager.GetString("processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wait while the command is processed.
        /// </summary>
        public static string processing_desc {
            get {
                return ResourceManager.GetString("processing_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Processing image.
        /// </summary>
        public static string processing_image {
            get {
                return ResourceManager.GetString("processing_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile.
        /// </summary>
        public static string profile {
            get {
                return ResourceManager.GetString("profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Protagonist.
        /// </summary>
        public static string protagonist {
            get {
                return ResourceManager.GetString("protagonist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Question.
        /// </summary>
        public static string question {
            get {
                return ResourceManager.GetString("question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Random kitten.
        /// </summary>
        public static string random_cat {
            get {
                return ResourceManager.GetString("random_cat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There was an error trying to retrieve the kitten.
        /// </summary>
        public static string random_cat_error {
            get {
                return ResourceManager.GetString("random_cat_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Random dog.
        /// </summary>
        public static string random_dog {
            get {
                return ResourceManager.GetString("random_dog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There was an error trying to retrieve the dog.
        /// </summary>
        public static string random_dog_error {
            get {
                return ResourceManager.GetString("random_dog_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registered.
        /// </summary>
        public static string registered {
            get {
                return ResourceManager.GetString("registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Related.
        /// </summary>
        public static string related {
            get {
                return ResourceManager.GetString("related", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The resource you were looking for was not found.
        /// </summary>
        public static string resource_not_found {
            get {
                return ResourceManager.GetString("resource_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Response timed out.
        /// </summary>
        public static string response_timed_out {
            get {
                return ResourceManager.GetString("response_timed_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Results.
        /// </summary>
        public static string results {
            get {
                return ResourceManager.GetString("results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Retrieved from.
        /// </summary>
        public static string retrieved_from {
            get {
                return ResourceManager.GetString("retrieved_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Retrieving.
        /// </summary>
        public static string retrieving {
            get {
                return ResourceManager.GetString("retrieving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Roles.
        /// </summary>
        public static string roles {
            get {
                return ResourceManager.GetString("roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Round.
        /// </summary>
        public static string round {
            get {
                return ResourceManager.GetString("round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rounds.
        /// </summary>
        public static string rounds {
            get {
                return ResourceManager.GetString("rounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remember that it only works with images that are part of an anime episode.
        /// </summary>
        public static string sauce_remember {
            get {
                return ResourceManager.GetString("sauce_remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Score.
        /// </summary>
        public static string score {
            get {
                return ResourceManager.GetString("score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can see the statistics using the /stats command.
        /// </summary>
        public static string see_stats {
            get {
                return ResourceManager.GetString("see_stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a genre.
        /// </summary>
        public static string select_a_genre {
            get {
                return ResourceManager.GetString("select_a_genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select an option.
        /// </summary>
        public static string select_an_option {
            get {
                return ResourceManager.GetString("select_an_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Set AniList profile.
        /// </summary>
        public static string set_anilist_profile {
            get {
                return ResourceManager.GetString("set_anilist_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Setup your AniList profile.
        /// </summary>
        public static string setup_anilist_profile {
            get {
                return ResourceManager.GetString("setup_anilist_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shutting down.
        /// </summary>
        public static string shutting_down {
            get {
                return ResourceManager.GetString("shutting_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Similarity.
        /// </summary>
        public static string similarity {
            get {
                return ResourceManager.GetString("similarity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start date.
        /// </summary>
        public static string start_date {
            get {
                return ResourceManager.GetString("start_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stats.
        /// </summary>
        public static string stats {
            get {
                return ResourceManager.GetString("stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Status.
        /// </summary>
        public static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Studio.
        /// </summary>
        public static string studio {
            get {
                return ResourceManager.GetString("studio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Studios.
        /// </summary>
        public static string studios {
            get {
                return ResourceManager.GetString("studios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Success.
        /// </summary>
        public static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sunrise.
        /// </summary>
        public static string sunrise {
            get {
                return ResourceManager.GetString("sunrise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sunset.
        /// </summary>
        public static string sunset {
            get {
                return ResourceManager.GetString("sunset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Synonyms.
        /// </summary>
        public static string synonyms {
            get {
                return ResourceManager.GetString("synonyms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tags.
        /// </summary>
        public static string tags {
            get {
                return ResourceManager.GetString("tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Talk with Yumiko.
        /// </summary>
        public static string talk_with_yumiko {
            get {
                return ResourceManager.GetString("talk_with_yumiko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Temperature.
        /// </summary>
        public static string temperature {
            get {
                return ResourceManager.GetString("temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The anime is: {0}.
        /// </summary>
        public static string the_anime_is {
            get {
                return ResourceManager.GetString("the_anime_is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The character is: {0} from {1}.
        /// </summary>
        public static string the_character_is {
            get {
                return ResourceManager.GetString("the_character_is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The manga is: {0}.
        /// </summary>
        public static string the_manga_is {
            get {
                return ResourceManager.GetString("the_manga_is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The possible anime of the image is.
        /// </summary>
        public static string the_possible_anime_is {
            get {
                return ResourceManager.GetString("the_possible_anime_is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The protagonists of {0} are:.
        /// </summary>
        public static string the_protagonists_of_are {
            get {
                return ResourceManager.GetString("the_protagonists_of_are", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The studios of {0} are:.
        /// </summary>
        public static string the_studios_of_are {
            get {
                return ResourceManager.GetString("the_studios_of_are", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tic-Tac-Toe.
        /// </summary>
        public static string tictactoe {
            get {
                return ResourceManager.GetString("tictactoe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tie!.
        /// </summary>
        public static string tie {
            get {
                return ResourceManager.GetString("tie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No one has managed to win.
        /// </summary>
        public static string tie_desc {
            get {
                return ResourceManager.GetString("tie_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Time.
        /// </summary>
        public static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Time to vote.
        /// </summary>
        public static string time_to_vote {
            get {
                return ResourceManager.GetString("time_to_vote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Timed out choosing genre.
        /// </summary>
        public static string timed_out_choosing_genre {
            get {
                return ResourceManager.GetString("timed_out_choosing_genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Title.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Titles language.
        /// </summary>
        public static string titles_language {
            get {
                return ResourceManager.GetString("titles_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To.
        /// </summary>
        public static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To vinculate your profile, you must use the following command.
        /// </summary>
        public static string to_vinculate_anilist_profile {
            get {
                return ResourceManager.GetString("to_vinculate_anilist_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total.
        /// </summary>
        public static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total servers.
        /// </summary>
        public static string total_guilds {
            get {
                return ResourceManager.GetString("total_guilds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total shards.
        /// </summary>
        public static string total_shards {
            get {
                return ResourceManager.GetString("total_shards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total users.
        /// </summary>
        public static string total_users {
            get {
                return ResourceManager.GetString("total_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type a letter!.
        /// </summary>
        public static string type_a_letter {
            get {
                return ResourceManager.GetString("type_a_letter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type /guess to make a guess.
        /// </summary>
        public static string type_guess_command {
            get {
                return ResourceManager.GetString("type_guess_command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unknown error.
        /// </summary>
        public static string unknown_error {
            get {
                return ResourceManager.GetString("unknown_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unknown error retrieving image from trace.moe.
        /// </summary>
        public static string unknown_error_tracemoe {
            get {
                return ResourceManager.GetString("unknown_error_tracemoe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Uptime.
        /// </summary>
        public static string uptime {
            get {
                return ResourceManager.GetString("uptime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please use this command in a age-restricted channel.
        /// </summary>
        public static string use_command_in_nsfw_channel {
            get {
                return ResourceManager.GetString("use_command_in_nsfw_channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0}&apos;s game statistics.
        /// </summary>
        public static string user_game_stats {
            get {
                return ResourceManager.GetString("user_game_stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a **{0}** has guessed!.
        /// </summary>
        public static string user_has_guessed {
            get {
                return ResourceManager.GetString("user_has_guessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} has made a mistake!.
        /// </summary>
        public static string user_made_a_mistake {
            get {
                return ResourceManager.GetString("user_made_a_mistake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User permission required.
        /// </summary>
        public static string user_permission_required {
            get {
                return ResourceManager.GetString("user_permission_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You need the `{0}` permission to execute this command.
        /// </summary>
        public static string user_permission_required_desc {
            get {
                return ResourceManager.GetString("user_permission_required_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0}&apos;s self love.
        /// </summary>
        public static string user_self_love {
            get {
                return ResourceManager.GetString("user_self_love", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} has won the game.
        /// </summary>
        public static string user_won_the_game {
            get {
                return ResourceManager.GetString("user_won_the_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Uses.
        /// </summary>
        public static string uses {
            get {
                return ResourceManager.GetString("uses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Victory!.
        /// </summary>
        public static string victory {
            get {
                return ResourceManager.GetString("victory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Video.
        /// </summary>
        public static string video {
            get {
                return ResourceManager.GetString("video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vote.
        /// </summary>
        public static string vote {
            get {
                return ResourceManager.GetString("vote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vote count.
        /// </summary>
        public static string vote_count {
            get {
                return ResourceManager.GetString("vote_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vote me in Top.gg!.
        /// </summary>
        public static string vote_me_on_topgg {
            get {
                return ResourceManager.GetString("vote_me_on_topgg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can help a lot by voting me in [this website]({0}). Thanks!.
        /// </summary>
        public static string vote_me_on_topgg_desc {
            get {
                return ResourceManager.GetString("vote_me_on_topgg_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vote made.
        /// </summary>
        public static string voted {
            get {
                return ResourceManager.GetString("voted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vote(s).
        /// </summary>
        public static string votes {
            get {
                return ResourceManager.GetString("votes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I am completely in love with you, when do we get married?.
        /// </summary>
        public static string waifu_level_100 {
            get {
                return ResourceManager.GetString("waifu_level_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I will shot myself before touch you.
        /// </summary>
        public static string waifu_level_25 {
            get {
                return ResourceManager.GetString("waifu_level_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You make me sick, I better get away from you.
        /// </summary>
        public static string waifu_level_50 {
            get {
                return ResourceManager.GetString("waifu_level_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You&apos;re not bad, maybe you have a chance with me.
        /// </summary>
        public static string waifu_level_75 {
            get {
                return ResourceManager.GetString("waifu_level_75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I am your waifu, you can do what you want with me.
        /// </summary>
        public static string waifu_level_99 {
            get {
                return ResourceManager.GetString("waifu_level_99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We have a winner!.
        /// </summary>
        public static string we_have_a_winner {
            get {
                return ResourceManager.GetString("we_have_a_winner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Weather.
        /// </summary>
        public static string weather {
            get {
                return ResourceManager.GetString("weather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Weather in.
        /// </summary>
        public static string weather_in {
            get {
                return ResourceManager.GetString("weather_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Website.
        /// </summary>
        public static string website {
            get {
                return ResourceManager.GetString("website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Which one has the best score?.
        /// </summary>
        public static string which_one_has_better_score {
            get {
                return ResourceManager.GetString("which_one_has_better_score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Which one is more popular?.
        /// </summary>
        public static string which_one_is_more_popular {
            get {
                return ResourceManager.GetString("which_one_is_more_popular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wind speed.
        /// </summary>
        public static string wind_speed {
            get {
                return ResourceManager.GetString("wind_speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Winner.
        /// </summary>
        public static string winner {
            get {
                return ResourceManager.GetString("winner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Without description).
        /// </summary>
        public static string without_description {
            get {
                return ResourceManager.GetString("without_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Without notes).
        /// </summary>
        public static string without_notes {
            get {
                return ResourceManager.GetString("without_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Without titles.
        /// </summary>
        public static string without_titles {
            get {
                return ResourceManager.GetString("without_titles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Write any letter to continue with the game.
        /// </summary>
        public static string write_any_letter_to_continue {
            get {
                return ResourceManager.GetString("write_any_letter_to_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wrong choice!.
        /// </summary>
        public static string wrong_choice {
            get {
                return ResourceManager.GetString("wrong_choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yes.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a YES OR NO?.
        /// </summary>
        public static string yes_or_no {
            get {
                return ResourceManager.GetString("yes_or_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You guessed it!.
        /// </summary>
        public static string you_guessed {
            get {
                return ResourceManager.GetString("you_guessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have cancelled the game!.
        /// </summary>
        public static string you_have_cancelled_the_game {
            get {
                return ResourceManager.GetString("you_have_cancelled_the_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You voted: `{0}`.
        /// </summary>
        public static string you_voted_to {
            get {
                return ResourceManager.GetString("you_voted_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your attempt.
        /// </summary>
        public static string your_attempt {
            get {
                return ResourceManager.GetString("your_attempt", resourceCulture);
            }
        }
    }
}
