//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yumiko {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yumiko.res.Translations.translations", typeof(translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied.
        /// </summary>
        public static string access_denied {
            get {
                return ResourceManager.GetString("access_denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action cancelled.
        /// </summary>
        public static string action_cancelled {
            get {
                return ResourceManager.GetString("action_cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action cannot be undone.
        /// </summary>
        public static string action_cannont_be_undone {
            get {
                return ResourceManager.GetString("action_cannont_be_undone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airing since {0}.
        /// </summary>
        public static string airing_since {
            get {
                return ResourceManager.GetString("airing_since", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anilist profile deleted successfully.
        /// </summary>
        public static string anilist_profile_deleted_successfully {
            get {
                return ResourceManager.GetString("anilist_profile_deleted_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anilist profile not found.
        /// </summary>
        public static string anilist_profile_not_found {
            get {
                return ResourceManager.GetString("anilist_profile_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Instructions**.
        /// </summary>
        public static string anilist_setprofile_instructions {
            get {
                return ResourceManager.GetString("anilist_setprofile_instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1- Click on the **Authorize** button.
        /// </summary>
        public static string anilist_setprofile_instructions_1 {
            get {
                return ResourceManager.GetString("anilist_setprofile_instructions_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2- Once the web page opens, click on the **Authorize** green button and then copy the text that will appear to copy.
        /// </summary>
        public static string anilist_setprofile_instructions_2 {
            get {
                return ResourceManager.GetString("anilist_setprofile_instructions_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3- Close the web page and click on the **Paste code here** button.
        /// </summary>
        public static string anilist_setprofile_instructions_3 {
            get {
                return ResourceManager.GetString("anilist_setprofile_instructions_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4- Paste the code in the modal and submit it.
        /// </summary>
        public static string anilist_setprofile_instructions_4 {
            get {
                return ResourceManager.GetString("anilist_setprofile_instructions_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animated.
        /// </summary>
        public static string animated {
            get {
                return ResourceManager.GetString("animated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anime.
        /// </summary>
        public static string anime {
            get {
                return ResourceManager.GetString("anime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anime list.
        /// </summary>
        public static string anime_list {
            get {
                return ResourceManager.GetString("anime_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anime stats.
        /// </summary>
        public static string anime_stats {
            get {
                return ResourceManager.GetString("anime_stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another trivia is already running in this channel.
        /// </summary>
        public static string another_trivia_playing {
            get {
                return ResourceManager.GetString("another_trivia_playing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to play a new trivia game, cancel de actual one or run this command on another channel.
        /// </summary>
        public static string another_trivia_playing_desc {
            get {
                return ResourceManager.GetString("another_trivia_playing_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string answer {
            get {
                return ResourceManager.GetString("answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorize.
        /// </summary>
        public static string authorize {
            get {
                return ResourceManager.GetString("authorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badges.
        /// </summary>
        public static string badges {
            get {
                return ResourceManager.GetString("badges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is an anime trivia bot, with other games and funcionalities.
        /// </summary>
        public static string bot_about {
            get {
                return ResourceManager.GetString("bot_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s guilds.
        /// </summary>
        public static string bot_guilds {
            get {
                return ResourceManager.GetString("bot_guilds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have left the `{0}` guild ({1}).
        /// </summary>
        public static string bot_left_guild {
            get {
                return ResourceManager.GetString("bot_left_guild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot permission required.
        /// </summary>
        public static string bot_permission_required {
            get {
                return ResourceManager.GetString("bot_permission_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} need the `{1}` permission to execute this command.
        /// </summary>
        public static string bot_permission_required_desc {
            get {
                return ResourceManager.GetString("bot_permission_required_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s statistics.
        /// </summary>
        public static string bot_stats {
            get {
                return ResourceManager.GetString("bot_stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cant play versus a bot.
        /// </summary>
        public static string cant_play_vs_bot {
            get {
                return ResourceManager.GetString("cant_play_vs_bot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chapters.
        /// </summary>
        public static string chapters {
            get {
                return ResourceManager.GetString("chapters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character.
        /// </summary>
        public static string character {
            get {
                return ResourceManager.GetString("character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character not found.
        /// </summary>
        public static string character_not_found {
            get {
                return ResourceManager.GetString("character_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to characters.
        /// </summary>
        public static string characters {
            get {
                return ResourceManager.GetString("characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an option.
        /// </summary>
        public static string choose_an_option {
            get {
                return ResourceManager.GetString("choose_an_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string code {
            get {
                return ResourceManager.GetString("code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string color {
            get {
                return ResourceManager.GetString("color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No command were used.
        /// </summary>
        public static string commands_not_used {
            get {
                return ResourceManager.GetString("commands_not_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands used.
        /// </summary>
        public static string commands_used {
            get {
                return ResourceManager.GetString("commands_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm that you want to delete your profile.
        /// </summary>
        public static string confirm_delete_profile {
            get {
                return ResourceManager.GetString("confirm_delete_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm if you really want to delete your stats.
        /// </summary>
        public static string confirm_delete_stats {
            get {
                return ResourceManager.GetString("confirm_delete_stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm that you want to save this profile.
        /// </summary>
        public static string confirm_save_profile {
            get {
                return ResourceManager.GetString("confirm_save_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation date.
        /// </summary>
        public static string creation_date {
            get {
                return ResourceManager.GetString("creation_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defeat!.
        /// </summary>
        public static string defeat {
            get {
                return ResourceManager.GetString("defeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have chosen not to delete their statistics.
        /// </summary>
        public static string delete_stats_cancelled {
            get {
                return ResourceManager.GetString("delete_stats_cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have deleted all your statistics on this guild.
        /// </summary>
        public static string delete_stats_done {
            get {
                return ResourceManager.GetString("delete_stats_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not press the button to write!.
        /// </summary>
        public static string did_not_press_button_to_write {
            get {
                return ResourceManager.GetString("did_not_press_button_to_write", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not write on time!.
        /// </summary>
        public static string did_not_write_on_time {
            get {
                return ResourceManager.GetString("did_not_write_on_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty.
        /// </summary>
        public static string difficulty {
            get {
                return ResourceManager.GetString("difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct message required.
        /// </summary>
        public static string dm_required {
            get {
                return ResourceManager.GetString("dm_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only execute this command in direct messages.
        /// </summary>
        public static string dm_required_desc {
            get {
                return ResourceManager.GetString("dm_required_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emote `{0}` not found.
        /// </summary>
        public static string emote_not_found {
            get {
                return ResourceManager.GetString("emote_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string end_date {
            get {
                return ResourceManager.GetString("end_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Episode.
        /// </summary>
        public static string episode {
            get {
                return ResourceManager.GetString("episode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Episodes.
        /// </summary>
        public static string episodes {
            get {
                return ResourceManager.GetString("episodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error retrieving the guild with the Id: `{0}`.
        /// </summary>
        public static string error_retrieving_guild_with_id {
            get {
                return ResourceManager.GetString("error_retrieving_guild_with_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example.
        /// </summary>
        public static string example {
            get {
                return ResourceManager.GetString("example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External &amp; Streaming links.
        /// </summary>
        public static string external_links {
            get {
                return ResourceManager.GetString("external_links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite animes.
        /// </summary>
        public static string favorite_animes {
            get {
                return ResourceManager.GetString("favorite_animes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite characters.
        /// </summary>
        public static string favorite_characters {
            get {
                return ResourceManager.GetString("favorite_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite mangas.
        /// </summary>
        public static string favorite_mangas {
            get {
                return ResourceManager.GetString("favorite_mangas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite staff.
        /// </summary>
        public static string favorite_staff {
            get {
                return ResourceManager.GetString("favorite_staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite studios.
        /// </summary>
        public static string favorite_studios {
            get {
                return ResourceManager.GetString("favorite_studios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feels like.
        /// </summary>
        public static string feels_like {
            get {
                return ResourceManager.GetString("feels_like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish game.
        /// </summary>
        public static string finish_game {
            get {
                return ResourceManager.GetString("finish_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string format {
            get {
                return ResourceManager.GetString("format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from the anime.
        /// </summary>
        public static string from_the_anime {
            get {
                return ResourceManager.GetString("from_the_anime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game cancelled.
        /// </summary>
        public static string game_cancelled {
            get {
                return ResourceManager.GetString("game_cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        public static string games {
            get {
                return ResourceManager.GetString("games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string genre {
            get {
                return ResourceManager.GetString("genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genres.
        /// </summary>
        public static string genres {
            get {
                return ResourceManager.GetString("genres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guess.
        /// </summary>
        public static string guess {
            get {
                return ResourceManager.GetString("guess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guess the.
        /// </summary>
        public static string guess_the {
            get {
                return ResourceManager.GetString("guess_the", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guess the anime.
        /// </summary>
        public static string guess_the_anime {
            get {
                return ResourceManager.GetString("guess_the_anime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guess the character.
        /// </summary>
        public static string guess_the_character {
            get {
                return ResourceManager.GetString("guess_the_character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guess the genre.
        /// </summary>
        public static string guess_the_genre {
            get {
                return ResourceManager.GetString("guess_the_genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guess the manga.
        /// </summary>
        public static string guess_the_manga {
            get {
                return ResourceManager.GetString("guess_the_manga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guess the protagonist.
        /// </summary>
        public static string guess_the_protagonist {
            get {
                return ResourceManager.GetString("guess_the_protagonist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guess the anime studio.
        /// </summary>
        public static string guess_the_studio {
            get {
                return ResourceManager.GetString("guess_the_studio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has guessed it!.
        /// </summary>
        public static string guess_user {
            get {
                return ResourceManager.GetString("guess_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guesses.
        /// </summary>
        public static string guesses {
            get {
                return ResourceManager.GetString("guesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guild required.
        /// </summary>
        public static string guild_required {
            get {
                return ResourceManager.GetString("guild_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only execute this command in a guild.
        /// </summary>
        public static string guild_required_desc {
            get {
                return ResourceManager.GetString("guild_required_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guild with id `{0}` not found.
        /// </summary>
        public static string guild_with_id_not_found {
            get {
                return ResourceManager.GetString("guild_with_id_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hangman.
        /// </summary>
        public static string hangman {
            get {
                return ResourceManager.GetString("hangman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the anime with the best score to win!.
        /// </summary>
        public static string higher_or_lower_desc {
            get {
                return ResourceManager.GetString("higher_or_lower_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **{0}** has lower avarage score **({1}/10)** than **{2} ({3}/10)**.
        /// </summary>
        public static string higher_or_lower_round_defeat {
            get {
                return ResourceManager.GetString("higher_or_lower_round_defeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **{0}** has **{1}/10** avarage score while **{2}** has **{3}/10**.
        /// </summary>
        public static string higher_or_lower_round_win {
            get {
                return ResourceManager.GetString("higher_or_lower_round_win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hint!.
        /// </summary>
        public static string hint {
            get {
                return ResourceManager.GetString("hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity.
        /// </summary>
        public static string humidity {
            get {
                return ResourceManager.GetString("humidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id `{0}` not valid.
        /// </summary>
        public static string id_not_valid {
            get {
                return ResourceManager.GetString("id_not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image extension must be JPG, PNG or JPEG.
        /// </summary>
        public static string image_format_error {
            get {
                return ResourceManager.GetString("image_format_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This image is from an adult anime.
        /// </summary>
        public static string image_from_nsfw_anime {
            get {
                return ResourceManager.GetString("image_from_nsfw_anime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter the link of an image.
        /// </summary>
        public static string image_must_enter_link {
            get {
                return ResourceManager.GetString("image_must_enter_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In english.
        /// </summary>
        public static string in_english {
            get {
                return ResourceManager.GetString("in_english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in popularity rank.
        /// </summary>
        public static string in_popularity_rank {
            get {
                return ResourceManager.GetString("in_popularity_rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite.
        /// </summary>
        public static string invite {
            get {
                return ResourceManager.GetString("invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join date.
        /// </summary>
        public static string join_date {
            get {
                return ResourceManager.GetString("join_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joined date.
        /// </summary>
        public static string joined_date {
            get {
                return ResourceManager.GetString("joined_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastest log file.
        /// </summary>
        public static string lastest_log_file {
            get {
                return ResourceManager.GetString("lastest_log_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latency.
        /// </summary>
        public static string latency {
            get {
                return ResourceManager.GetString("latency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letters used.
        /// </summary>
        public static string letters_used {
            get {
                return ResourceManager.GetString("letters_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        public static string library {
            get {
                return ResourceManager.GetString("library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string link {
            get {
                return ResourceManager.GetString("link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location `{0}, {1}` not found.
        /// </summary>
        public static string location_not_found {
            get {
                return ResourceManager.GetString("location_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get away! You two are going to kill each other.
        /// </summary>
        public static string love_0 {
            get {
                return ResourceManager.GetString("love_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to They will hate each other, they are not compatible at all.
        /// </summary>
        public static string love_10 {
            get {
                return ResourceManager.GetString("love_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfect relationship! They will marry and have many children.
        /// </summary>
        public static string love_100 {
            get {
                return ResourceManager.GetString("love_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is best that they move away from each other, they do not fit.
        /// </summary>
        public static string love_25 {
            get {
                return ResourceManager.GetString("love_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to They will be good friends, but I find love difficult.
        /// </summary>
        public static string love_50 {
            get {
                return ResourceManager.GetString("love_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most likely they are best friends and hopefully something more.
        /// </summary>
        public static string love_75 {
            get {
                return ResourceManager.GetString("love_75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to They have to give themselves a chance.
        /// </summary>
        public static string love_90 {
            get {
                return ResourceManager.GetString("love_90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You two are meant to be together.
        /// </summary>
        public static string love_99 {
            get {
                return ResourceManager.GetString("love_99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Love between **{0}** and **{1}**.
        /// </summary>
        public static string love_between {
            get {
                return ResourceManager.GetString("love_between", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manga.
        /// </summary>
        public static string manga {
            get {
                return ResourceManager.GetString("manga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manga list.
        /// </summary>
        public static string manga_list {
            get {
                return ResourceManager.GetString("manga_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manga stats.
        /// </summary>
        public static string manga_stats {
            get {
                return ResourceManager.GetString("manga_stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean score.
        /// </summary>
        public static string mean_score {
            get {
                return ResourceManager.GetString("mean_score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} recommendations.
        /// </summary>
        public static string media_recommendations {
            get {
                return ResourceManager.GetString("media_recommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explanation: The higher the number, the more likely you are to like it. Recommendations are calculated based on your watched {0}s and the scores you have assigned to them..
        /// </summary>
        public static string media_recommendations_explanation {
            get {
                return ResourceManager.GetString("media_recommendations_explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s avatar.
        /// </summary>
        public static string member_avatar {
            get {
                return ResourceManager.GetString("member_avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member count.
        /// </summary>
        public static string member_count {
            get {
                return ResourceManager.GetString("member_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory usage.
        /// </summary>
        public static string memory_usage {
            get {
                return ResourceManager.GetString("memory_usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message.
        /// </summary>
        public static string message {
            get {
                return ResourceManager.GetString("message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This message will not be triggered if the user has voted in the past 12 hours.
        /// </summary>
        public static string message_will_not_be_triggered {
            get {
                return ResourceManager.GetString("message_will_not_be_triggered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min/Max.
        /// </summary>
        public static string min_max {
            get {
                return ResourceManager.GetString("min_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        public static string minute {
            get {
                return ResourceManager.GetString("minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, wrong choice!.
        /// </summary>
        public static string miss_user_games {
            get {
                return ResourceManager.GetString("miss_user_games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, you must enter the URL of your Anilist profile.
        /// </summary>
        public static string must_enter_anilist_profile_url {
            get {
                return ResourceManager.GetString("must_enter_anilist_profile_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My love to **{0}** is **{1}%**.
        /// </summary>
        public static string my_love_to_user_is {
            get {
                return ResourceManager.GetString("my_love_to_user_is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, you decided to not save your Anilist profile.
        /// </summary>
        public static string new_profile_cancelled_mention {
            get {
                return ResourceManager.GetString("new_profile_cancelled_mention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New profile saved successfully.
        /// </summary>
        public static string new_profile_saved {
            get {
                return ResourceManager.GetString("new_profile_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, you have successfully saved your Anilist profile.
        /// </summary>
        public static string new_profile_saved_mention {
            get {
                return ResourceManager.GetString("new_profile_saved_mention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New record.
        /// </summary>
        public static string new_record {
            get {
                return ResourceManager.GetString("new_record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations {0}! You have beaten your best score.\n\nYour new record is: **{1}**.
        /// </summary>
        public static string new_record_desc {
            get {
                return ResourceManager.GetString("new_record_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no active game in this channel.
        /// </summary>
        public static string no_active_game {
            get {
                return ResourceManager.GetString("no_active_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No air date available.
        /// </summary>
        public static string no_air_date {
            get {
                return ResourceManager.GetString("no_air_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, you don&apos;t have any Anilist profile vinculated .
        /// </summary>
        public static string no_anilist_profile_vinculated {
            get {
                return ResourceManager.GetString("no_anilist_profile_vinculated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seconds have passed and no answer has been given in time.
        /// </summary>
        public static string no_answser_in_time {
            get {
                return ResourceManager.GetString("no_answser_in_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nobody has clicked any button.
        /// </summary>
        public static string no_click_button {
            get {
                return ResourceManager.GetString("no_click_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no trivia in this channel.
        /// </summary>
        public static string no_current_trivia {
            get {
                return ResourceManager.GetString("no_current_trivia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No genre has been selected.
        /// </summary>
        public static string no_genre_selected {
            get {
                return ResourceManager.GetString("no_genre_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No logs found.
        /// </summary>
        public static string no_logs_found {
            get {
                return ResourceManager.GetString("no_logs_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No recommendations were found.\nThis is probably because you have few entries in your list or do not have a score assigned to them..
        /// </summary>
        public static string no_recommendations_found {
            get {
                return ResourceManager.GetString("no_recommendations_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found for this image.
        /// </summary>
        public static string no_results_found_image {
            get {
                return ResourceManager.GetString("no_results_found_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not played any game yet.
        /// </summary>
        public static string no_stats_available {
            get {
                return ResourceManager.GetString("no_stats_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nobody has guessed.
        /// </summary>
        public static string nobody_has_guessed {
            get {
                return ResourceManager.GetString("nobody_has_guessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not assigned.
        /// </summary>
        public static string not_assigned {
            get {
                return ResourceManager.GetString("not_assigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not found.
        /// </summary>
        public static string not_found {
            get {
                return ResourceManager.GetString("not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No yet released.
        /// </summary>
        public static string not_yet_released {
            get {
                return ResourceManager.GetString("not_yet_released", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string notes {
            get {
                return ResourceManager.GetString("notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string of {
            get {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the bot owner can execute this command.
        /// </summary>
        public static string only_bot_owner {
            get {
                return ResourceManager.GetString("only_bot_owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string options {
            get {
                return ResourceManager.GetString("options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste code here.
        /// </summary>
        public static string paste_code_here {
            get {
                return ResourceManager.GetString("paste_code_here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission required.
        /// </summary>
        public static string permission_required {
            get {
                return ResourceManager.GetString("permission_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You and {0} needs the `{1}` permission to execute this command.
        /// </summary>
        public static string permission_required_desc {
            get {
                return ResourceManager.GetString("permission_required_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s turn.
        /// </summary>
        public static string player_turn {
            get {
                return ResourceManager.GetString("player_turn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while everything is prepared.
        /// </summary>
        public static string please_wait {
            get {
                return ResourceManager.GetString("please_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressure.
        /// </summary>
        public static string pressure {
            get {
                return ResourceManager.GetString("pressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string privacy_policy {
            get {
                return ResourceManager.GetString("privacy_policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string processing {
            get {
                return ResourceManager.GetString("processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait while the command is processed.
        /// </summary>
        public static string processing_desc {
            get {
                return ResourceManager.GetString("processing_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing image.
        /// </summary>
        public static string processing_image {
            get {
                return ResourceManager.GetString("processing_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string profile {
            get {
                return ResourceManager.GetString("profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protagonist.
        /// </summary>
        public static string protagonist {
            get {
                return ResourceManager.GetString("protagonist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publication date.
        /// </summary>
        public static string publication_date {
            get {
                return ResourceManager.GetString("publication_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string question {
            get {
                return ResourceManager.GetString("question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random kitten.
        /// </summary>
        public static string random_cat {
            get {
                return ResourceManager.GetString("random_cat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error trying to retrieve the kitten.
        /// </summary>
        public static string random_cat_error {
            get {
                return ResourceManager.GetString("random_cat_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random dog.
        /// </summary>
        public static string random_dog {
            get {
                return ResourceManager.GetString("random_dog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error trying to retrieve the dog.
        /// </summary>
        public static string random_dog_error {
            get {
                return ResourceManager.GetString("random_dog_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered.
        /// </summary>
        public static string registered {
            get {
                return ResourceManager.GetString("registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related.
        /// </summary>
        public static string related {
            get {
                return ResourceManager.GetString("related", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response timed out.
        /// </summary>
        public static string response_timed_out {
            get {
                return ResourceManager.GetString("response_timed_out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string results {
            get {
                return ResourceManager.GetString("results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieved from.
        /// </summary>
        public static string retrieved_from {
            get {
                return ResourceManager.GetString("retrieved_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving.
        /// </summary>
        public static string retrieving {
            get {
                return ResourceManager.GetString("retrieving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string roles {
            get {
                return ResourceManager.GetString("roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round.
        /// </summary>
        public static string round {
            get {
                return ResourceManager.GetString("round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rounds.
        /// </summary>
        public static string rounds {
            get {
                return ResourceManager.GetString("rounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember that it only works with images that are part of an anime episode.
        /// </summary>
        public static string sauce_remember {
            get {
                return ResourceManager.GetString("sauce_remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string score {
            get {
                return ResourceManager.GetString("score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can see the statistics using the /stats command.
        /// </summary>
        public static string see_stats {
            get {
                return ResourceManager.GetString("see_stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a genre.
        /// </summary>
        public static string select_a_genre {
            get {
                return ResourceManager.GetString("select_a_genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an option.
        /// </summary>
        public static string select_an_option {
            get {
                return ResourceManager.GetString("select_an_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set AniList profile.
        /// </summary>
        public static string set_anilist_profile {
            get {
                return ResourceManager.GetString("set_anilist_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup your AniList profile.
        /// </summary>
        public static string setup_anilist_profile {
            get {
                return ResourceManager.GetString("setup_anilist_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutting down.
        /// </summary>
        public static string shutting_down {
            get {
                return ResourceManager.GetString("shutting_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similarity.
        /// </summary>
        public static string similarity {
            get {
                return ResourceManager.GetString("similarity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string start_date {
            get {
                return ResourceManager.GetString("start_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stats.
        /// </summary>
        public static string stats {
            get {
                return ResourceManager.GetString("stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studio.
        /// </summary>
        public static string studio {
            get {
                return ResourceManager.GetString("studio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studios.
        /// </summary>
        public static string studios {
            get {
                return ResourceManager.GetString("studios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunrise.
        /// </summary>
        public static string sunrise {
            get {
                return ResourceManager.GetString("sunrise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunset.
        /// </summary>
        public static string sunset {
            get {
                return ResourceManager.GetString("sunset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synonyms.
        /// </summary>
        public static string synonyms {
            get {
                return ResourceManager.GetString("synonyms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string tags {
            get {
                return ResourceManager.GetString("tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string temperature {
            get {
                return ResourceManager.GetString("temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The anime is: {0}.
        /// </summary>
        public static string the_anime_is {
            get {
                return ResourceManager.GetString("the_anime_is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The character is: {0} from {1}.
        /// </summary>
        public static string the_character_is {
            get {
                return ResourceManager.GetString("the_character_is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The manga is: {0}.
        /// </summary>
        public static string the_manga_is {
            get {
                return ResourceManager.GetString("the_manga_is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The possible anime of the image is.
        /// </summary>
        public static string the_possible_anime_is {
            get {
                return ResourceManager.GetString("the_possible_anime_is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The protagonists of {0} are:.
        /// </summary>
        public static string the_protagonists_of_are {
            get {
                return ResourceManager.GetString("the_protagonists_of_are", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The studios of {0} are:.
        /// </summary>
        public static string the_studios_of_are {
            get {
                return ResourceManager.GetString("the_studios_of_are", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tic-Tac-Toe.
        /// </summary>
        public static string tictactoe {
            get {
                return ResourceManager.GetString("tictactoe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tie!.
        /// </summary>
        public static string tie {
            get {
                return ResourceManager.GetString("tie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No one has managed to win.
        /// </summary>
        public static string tie_desc {
            get {
                return ResourceManager.GetString("tie_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timed out choosing genre.
        /// </summary>
        public static string timed_out_choosing_genre {
            get {
                return ResourceManager.GetString("timed_out_choosing_genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titles language.
        /// </summary>
        public static string titles_language {
            get {
                return ResourceManager.GetString("titles_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To vinculate your profile, you must use the following command.
        /// </summary>
        public static string to_vinculate_anilist_profile {
            get {
                return ResourceManager.GetString("to_vinculate_anilist_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total guilds.
        /// </summary>
        public static string total_guilds {
            get {
                return ResourceManager.GetString("total_guilds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total shards.
        /// </summary>
        public static string total_shards {
            get {
                return ResourceManager.GetString("total_shards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total users.
        /// </summary>
        public static string total_users {
            get {
                return ResourceManager.GetString("total_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a letter!.
        /// </summary>
        public static string type_a_letter {
            get {
                return ResourceManager.GetString("type_a_letter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        public static string unknown_error {
            get {
                return ResourceManager.GetString("unknown_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error retrieving image from trace.moe.
        /// </summary>
        public static string unknown_error_tracemoe {
            get {
                return ResourceManager.GetString("unknown_error_tracemoe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uptime.
        /// </summary>
        public static string uptime {
            get {
                return ResourceManager.GetString("uptime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please use this command in a age-restricted channel.
        /// </summary>
        public static string use_command_in_nsfw_channel {
            get {
                return ResourceManager.GetString("use_command_in_nsfw_channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s game statistics.
        /// </summary>
        public static string user_game_stats {
            get {
                return ResourceManager.GetString("user_game_stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **{0}** has guessed!.
        /// </summary>
        public static string user_has_guessed {
            get {
                return ResourceManager.GetString("user_has_guessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has made a mistake!.
        /// </summary>
        public static string user_made_a_mistake {
            get {
                return ResourceManager.GetString("user_made_a_mistake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User permission required.
        /// </summary>
        public static string user_permission_required {
            get {
                return ResourceManager.GetString("user_permission_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need the `{0}` permission to execute this command.
        /// </summary>
        public static string user_permission_required_desc {
            get {
                return ResourceManager.GetString("user_permission_required_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s self love.
        /// </summary>
        public static string user_self_love {
            get {
                return ResourceManager.GetString("user_self_love", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has won the game.
        /// </summary>
        public static string user_won_the_game {
            get {
                return ResourceManager.GetString("user_won_the_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uses.
        /// </summary>
        public static string uses {
            get {
                return ResourceManager.GetString("uses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Victory!.
        /// </summary>
        public static string victory {
            get {
                return ResourceManager.GetString("victory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string video {
            get {
                return ResourceManager.GetString("video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote.
        /// </summary>
        public static string vote {
            get {
                return ResourceManager.GetString("vote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote me in Top.gg!.
        /// </summary>
        public static string vote_me_on_topgg {
            get {
                return ResourceManager.GetString("vote_me_on_topgg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can help a lot by voting me in [this website]({0}). Thanks!.
        /// </summary>
        public static string vote_me_on_topgg_desc {
            get {
                return ResourceManager.GetString("vote_me_on_topgg_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am completely in love with you, when do we get married?.
        /// </summary>
        public static string waifu_level_100 {
            get {
                return ResourceManager.GetString("waifu_level_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I will shot myself before touch you.
        /// </summary>
        public static string waifu_level_25 {
            get {
                return ResourceManager.GetString("waifu_level_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You make me sick, I better get away from you.
        /// </summary>
        public static string waifu_level_50 {
            get {
                return ResourceManager.GetString("waifu_level_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re not bad, maybe you have a chance with me.
        /// </summary>
        public static string waifu_level_75 {
            get {
                return ResourceManager.GetString("waifu_level_75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am your waifu, you can do what you want with me.
        /// </summary>
        public static string waifu_level_99 {
            get {
                return ResourceManager.GetString("waifu_level_99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have a winner!.
        /// </summary>
        public static string we_have_a_winner {
            get {
                return ResourceManager.GetString("we_have_a_winner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather.
        /// </summary>
        public static string weather {
            get {
                return ResourceManager.GetString("weather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather in.
        /// </summary>
        public static string weather_in {
            get {
                return ResourceManager.GetString("weather_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string website {
            get {
                return ResourceManager.GetString("website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which one has the best score?.
        /// </summary>
        public static string which_one_has_better_score {
            get {
                return ResourceManager.GetString("which_one_has_better_score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind speed.
        /// </summary>
        public static string wind_speed {
            get {
                return ResourceManager.GetString("wind_speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winner.
        /// </summary>
        public static string winner {
            get {
                return ResourceManager.GetString("winner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Without animes or mangas).
        /// </summary>
        public static string without_animes_or_mangas {
            get {
                return ResourceManager.GetString("without_animes_or_mangas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Without description).
        /// </summary>
        public static string without_description {
            get {
                return ResourceManager.GetString("without_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Without notes).
        /// </summary>
        public static string without_notes {
            get {
                return ResourceManager.GetString("without_notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without titles.
        /// </summary>
        public static string without_titles {
            get {
                return ResourceManager.GetString("without_titles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write any letter to continue with the game.
        /// </summary>
        public static string write_any_letter_to_continue {
            get {
                return ResourceManager.GetString("write_any_letter_to_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong choice!.
        /// </summary>
        public static string wrong_choice {
            get {
                return ResourceManager.GetString("wrong_choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YES OR NO?.
        /// </summary>
        public static string yes_or_no {
            get {
                return ResourceManager.GetString("yes_or_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You guessed it!.
        /// </summary>
        public static string you_guessed {
            get {
                return ResourceManager.GetString("you_guessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have cancelled the game!.
        /// </summary>
        public static string you_have_cancelled_the_game {
            get {
                return ResourceManager.GetString("you_have_cancelled_the_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Anilist profile is.
        /// </summary>
        public static string your_anilist_profile_is {
            get {
                return ResourceManager.GetString("your_anilist_profile_is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your attempt.
        /// </summary>
        public static string your_attempt {
            get {
                return ResourceManager.GetString("your_attempt", resourceCulture);
            }
        }
    }
}
